name: CD

on:
  push:
  pull_request:

permissions:
  contents: write

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    concurrency: cd-${{ github.ref }}

    steps:
      - name: Deploy
        run: curl -X POST https://voyago-refresh.namikas.dev/webhook
