name: refresh

on:
  push:
  pull_request:

jobs:
  notify_server:
    runs-on: ubuntu-latest

    steps:
      - name: Send POST request to server
        run: curl -X POST https://voyago-refresh.namikas.dev
